In [9]:
import streamlit as st
import numpy as np
import pandas as pd

st.title('Streamlit 超入門')

st.write('DataFrame')

In [17]:
df = pd.DataFrame(
    np.random.rand(100, 2)/[50, 50] + [35.69,139.70],
    columns=['lat','lon']
)
df

          lat         lon
0   35.699529  139.716104
1   35.703969  139.714001
2   35.703503  139.707054
3   35.701989  139.719644
4   35.697789  139.706033
..        ...         ...
95  35.694067  139.708955
96  35.698637  139.701100
97  35.704434  139.714443
98  35.709125  139.708489
99  35.707908  139.708450

[100 rows x 2 columns]